name: CI Pipeline

on:
  push:
  # Habilita o gatilho manual atraves da interface do Github Actions
  workflow_dispatch:

jobs:
  # Job para a execucao dos testes
  tests:
    name: Tests Runner
    runs-on: ubuntu-latest
    # Configuracao de passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 2. Executar os testes da aplicacao
      - name: Run application tests
        run: ./gradlew test